beautysh: re-format
beautysh is enabled in the openbmc-build-scripts on Bash/Zsh/POSIX-sh
files to have a consistent formatting.  Re-run the formatter on the
whole repository.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: I584c76da2eb35af2177a97d5cd4b882f9881fb80

diff --git a/templates/bash_simple_template b/templates/bash_simple_template
--- a/templates/bash_simple_template
+++ b/templates/bash_simple_template
@@ -8,56 +8,56 @@
 # parm1                             Bla, bla, bla (e.g. "example data").
 
 
-function get_parms {
+function get_parms() {
 
-  # Get program parms.
+    # Get program parms.
 
-  parm1="${1}" ; shift
+    parm1="${1}" ; shift
 
-  return 0
-
-}
-
-
-function exit_function {
-
-  return
-
-}
-
-function validate_parms {
-
-  # Validate program parameters.
-
-  # Your validation code here.
-
-  if [ -z "${parm1}" ] ; then
-    echo "**ERROR** You must provide..." >&2
-    return 1
-  fi
-
-  trap "exit_function $signal \$?" EXIT
-
-  return 0
+    return 0
 
 }
 
 
-function mainf {
+function exit_function() {
 
-  get_parms "$@" || return 1
+    return
 
-  validate_parms || return 1
+}
 
-  # Your code here...
+function validate_parms() {
 
-  return 0
+    # Validate program parameters.
+
+    # Your validation code here.
+
+    if [ -z "${parm1}" ] ; then
+        echo "**ERROR** You must provide..." >&2
+        return 1
+    fi
+
+    trap "exit_function $signal \$?" EXIT
+
+    return 0
+
+}
+
+
+function mainf() {
+
+    get_parms "$@" || return 1
+
+    validate_parms || return 1
+
+    # Your code here...
+
+    return 0
 
 }
 
 
 # Main
 
-  mainf "${@}"
-  rc="${?}"
-  exit "${rc}"
+mainf "${@}"
+rc="${?}"
+exit "${rc}"
diff --git a/tools/convert_ip_to_dummy b/tools/convert_ip_to_dummy
--- a/tools/convert_ip_to_dummy
+++ b/tools/convert_ip_to_dummy
@@ -14,15 +14,15 @@ file_path="${1}" ; shift
 
 # Validate arguments.
 if [ -z "${ip_addr}" ] ; then
-  echo "**ERROR** You must provide an IP address as the first positional" \
-       "parameter." >&2
-  exit 1
+    echo "**ERROR** You must provide an IP address as the first positional" \
+        "parameter." >&2
+    exit 1
 fi
 
 if [ -z "${file_path}" ] ; then
-  echo "**ERROR** You must provide a file path as the second positional" \
-       "parameter." >&2
-  exit 1
+    echo "**ERROR** You must provide a file path as the second positional" \
+        "parameter." >&2
+    exit 1
 fi
 
 ip_addr_regex=`echo ${ip_addr} | sed 's/\(\.\)/\\\./g'`
